### PR TITLE
Use adaptive icons for shortcuts

### PR DESCRIPTION
**Pull request by mueller-ma**
I wasn't able to use the assets in orig folder, so I used an icon from
materialdesignicons.com.

Signed-off-by: mueller-ma <mueller-ma@users.noreply.github.com>

### CODE REVIEW

**Comment by mueller-ma** [comment]
@adrian-bl May I ask for a review?

**Comment by adrian-bl** [comment]
Does this still work on our min-api level?

**Comment by mueller-ma** [comment]
I haven't tested it, but I guess so. The adaptive icon is under mipmap-anydpi-v26 and the legacy one is under mipmap-[mhx...]-dpi. So for api < 26 the old icons are used.

**Comment by mueller-ma** [comment]
@adrian-bl What's the review state of this PR? Shortcuts work fine on devices with legacy icons and on devices with adaptive icons.

**Comment by mueller-ma** [comment]
Closed due to no activity

**Pull request closed without merging**
