### PR TITLE
Gradle-related updates

### PR DESCRIPTION
**Pull request by relan**
Bump versions of build tools, Gradle plugin and Gradle wrapper.

Note the `distributionSha256Sum` field: the downloaded Gradle distribution will be validated using this hash.

### CODE REVIEW

**Comment by adrian-bl** [comment]
I'm not a gradle user, but looks fine to me -> merging :-)

**Comment by relan** [comment]
BTW, why are there 2 build systems? Do you plan to switch to Gradle one day?

**Comment by adrian-bl** [comment]
No: I do not plan to switch to gradle anytime soon - ant will stay the 'primary' build system.

We just have gradle support because some users like it and it is low maintenance work

**Comment by relan** [comment]
Got it. I thought Gradle was a primary build system because it was #1 in the README.

**Pull request merged**
