### PR TITLE
Small translation improvements

### PR DESCRIPTION
**Pull request by pejakm**
* Added few more strings to improve context handling of swap option list for some languages (Serbian, for example)
 * Use 'None' instead of 'Do nothing' ("Default action" implies name of an action, not what to do). Fits better and also may improve context for some languages

### CODE REVIEW

**Comment by pejakm** [comment]
Any thoughts on this?

**Comment by adrian-bl** [comment]
I do not see why the patch adds new keys for already translated strings. Or am i missing something?

**Comment by pejakm** [comment]
@adrian-bl Sorry for late reply, I missed the notification of your reply. Like I've explained in commit note, it improves the context for languages other than English. For example, it makes sense to have `clear_queue` translated differently for queue list (infinitive) and for main menu (imperative).

**Comment by adrian-bl** [comment]
Ok, i see your point:
I added the new keys in commit https://github.com/vanilla-music/vanilla/commit/61bcb9857a7799437bfca00da63b844cc70d2db2

Note that, for now, this only adds the new keys: The should show up on Transifex in the next ~24h hours.

I'll change the entries in 'untranslatable.xml' after the strings got translated in the most common languages. (and i'll keep the PR open as a reminder for myself)

**Comment by pejakm** [comment]
Thank you very much!

**Comment by adrian-bl** [comment]
Closing this: We are now using the new preferences_action_ strings in settings

**Pull request closed without merging**
