### PR TITLE
Use darker colors for artist images

### LINKED ISSUE #983: FR: Darker colors for artist images on dark themes
- Vanilla Music Version (Settings -> About): 1.0.83
- Android Version: 7
- Phone vendor / model: Oneplus X
- Application was downloaded from:
  - [ ] Play Store
  - [x] F-Droid
  - [ ] Other (Nightly Build)
- Did this work in a previous version?
  - [ ] Yes
  - [ ] No
  - [x] NA / Don't know

## Description

IMO the colors of the background of the icons next to each artist in the artist or album artist view are too bright in the dark themes.
I suggest to add a second set of colors, that are darker than the current ones, used in dark themes.

### PR DESCRIPTION
**Pull request by mueller-ma**
Fixes #983

### CODE REVIEW

**Comment by adrian-bl** [comment]
Is this based on an official color palette?

We are currently using the material color palette - which seems to be a sane choice for android.

**Comment by mueller-ma** [comment]
I used a website to make the colors 20% darker. Some of them 40%, because 20% wasn't enough.
You're talking about the color table on https://material.io/design/color/the-color-system.html ? I wasn't aware the current colors are based on these colors.
I can update the new dark colors according to the material color palettes.

**Comment by mueller-ma** [comment]
@adrian-bl I updated the colors. The dark colors are now based on material colors if the bright equivalent is also a material color.

**Comment by adrian-bl** [comment]
thanks, but could you also update 'generate-themes.pl' which is used to assemble the theme XML files?

Did you also test this on api versions < v21?

**Comment by mueller-ma** [comment]
> thanks, but could you also update 'generate-themes.pl' which is used to assemble the theme XML files?

Done!

> Did you also test this on api versions < v21?

No, I didn't. I try to find a device <v21 with music on it.

**Comment by mueller-ma** [comment]
> No, I didn't. I try to find a device <v21 with music on it.

I haven't found a suitable device.

**Comment by adrian-bl** [comment]
I found an android 4.4 device and things seem to work fine - merging.
Thanks!

**Pull request merged**
