### PR TITLE
All files access permission

### LINKED ISSUE #1142: Playlists not exporting
- Vanilla Music Version (Settings -> About): 1.1.0
- Android Version: 11 (Lineage OS)
- Phone vendor / model: OnePlus 9
- Application was downloaded from (use `[x]`):
  - [ ] Play Store
  - [x] F-Droid
  - [ ] Other (Nightly Build)
- Did this work in a previous version?
  - [ ] Yes
  - [ ] No
  - [x] NA / Don't know.

## Description
I am not able to export playlists. 
....

## Steps to reproduce the issue
Select "Full synchronization".
Select folder for playlists to synchronize from/to. 
None of the playlists I have created in Vanilla Music appear in that folder. 
I have created M3U files in vlc on linux, and copied them to the Android folder I selected for playlist synchronization, and they import to vanilla music. If I edit them in Vanilla, the changes are not reflected in the M3U file.

### PR DESCRIPTION
**Pull request by reactorcoremeltdown**
Fixes #1142

### CODE REVIEW

**Comment by adrian-bl** [comment]
How does that work? Don't we have to ask for this permission first?

**Comment by reactorcoremeltdown** [comment]
@adrian-bl it does not explicitly ask for the permission, but allows for selecting it in the application's properties.

image

If a dialogue for requesting exactly this permission is required, I'll try my best to submit a patch. Just let me know!

**Comment by adrian-bl** [comment]
Since this is about exporting playlists: Maybe we could add something in the settings?

If the permission is not granted, we could show an option to open the preferences and grant permissions. wdyt? (I doubt that users would figure out that on their own)

**Comment by reactorcoremeltdown** [comment]
Makes sense! I am mostly a monkeypatcher, I have zero experience in Java, but I am clever enough to see how others do that. I'll try to add a menu item in that activity and get back to you!

**Comment by reactorcoremeltdown** [comment]
@adrian-bl I finally made it, please review.

screen-20230425-203509 mp4

**Comment by adrian-bl** [comment]
thanks, lgtm! Lets merge this and give it a go

**Comment by adrian-bl** [comment]
Well, unfortunately i need to roll this back :-/

Seems that the play store won't allow me to upload an APK which requests this permission:

image

And i don't think we qualify for an exemption: https://support.google.com/googleplay/android-developer/answer/10467955?visit_id=638184408302430276-147505165&rd=1#zippy=%2Cpermitted-uses-of-the-all-files-access-permission

It therefore seems that the only way out here is to use SAF or somehow find another way to write the files without making Android unhappy

**Comment by xeruf** [comment]
Is there an APK build available for the meantime?

**Comment by reactorcoremeltdown** [comment]
@adrian-bl I totally understand your concerns and will try my best to address it. Thank you very much 

@xeruf while I can easily build an apk and hand it over to you, I think it can cause problems like conflicting signing keys.

I think a middle ground solution could be publishing a nightly apk, or a pre-release to F-Droid. I understand the concerns also here (adding and removing a feature with a potential of breaking it), but at the same time we're introducing a 100% opt-in feature that we can phase out later on. @adrian-bl wdyt?

**Comment by xeruf** [comment]
That sounds good, I use F-Droid anyways :)

**Comment by jameskirkwood** [comment]
@adrian-bl I observed the same on hardware with your implementation. It's also not possible to overwrite or delete playlists created through MTP either. However it is possible to create a writable copy by renaming in Vanilla. One can then delete the original externally and use Vanilla to rename the copy back to its original name. Renaming over the top of an externally owned file using Vanilla seems to have no effect other than replacing the Vanilla owned file with a backup.

I can deal with this limitation but it would be ideal if the externally owned or otherwise unwritable playlists were recognised as such, and any actions that would attempt to overwrite or delete them disabled, except perhaps 'rename' which essentially becomes 'make a copy'. Although, the latter would be a handy operation to also allow for Vanilla owned playlists.

If someone tries to modify a playlist and it fails, it would be helpful to prompt for a different name so they can at least save their change and maybe later delete the old one and rename the copy if they want.

**Pull request merged**
