### PR TITLE
Add 'Download Nightly' menu item to nightly builds

### PR DESCRIPTION
**Pull request by xbao**
Looking for feedback on this idea (making the nightly build easier to update) and the approach.

### CODE REVIEW

**Comment by adrian-bl** [comment]
That's a nice idea, but i feel that having this in the code is somewhat overblown ;-)
@aminb What do you think?

How about adding a link to it in the about section?
This could also be included in release builds - oh: and reminds me that i wanted to invest some time in the vanillamusic.io design :-)

**Comment by aminb** [comment]
Nice idea, but like Adrian said I'm not sure if I'd really want to add a menu item for it on Library Activity. Because then I'd like to have an option to disable that menu item, and *that* would be an overkill. However, I do think the about section is a bit inaccessible at the moment.

So, how about we add an 'About' menu item to Library activity instead, and add the link to latest nightly in the about page?

**Comment by adrian-bl** [comment]
> So, how about we add an 'About' menu item to Library activity instead, and add the link to latest nightly in
> the about page?

I wouldn't do that: How often does one use the 'About' menu? A normal user probably never will click on it, so there is no point in having a shortcut to it.

**Comment by aminb** [comment]
Well, that's exactly my point :) Right now, very few people might check the About page, because it's 'hidden' in the Settings page and unless they want to change some setting, they won't go to Settings. And even then, when they open up Settings, they are probably there for something else, not for looking at the About page.

But if we add it to the menu, it'll be more accessible and I think more people will be encouraged to take a look at it (to see the changelogs of their music app, its contributors, and perhaps a link to its latest nightly).

IMHO 'About' is not a setting so from that point of view doesn't make much sense to be in 'Settings' either.

**Comment by adrian-bl** [comment]
> But if we add it to the menu, it'll be more accessible and I think more people will be encouraged to take a 
> look at it (to see the changelogs of their music app, its contributors, and perhaps a link to its latest nightly).

This might be true for f-droid users, but the majority of users just wont' care.
Also: Having the 'About' section in the Settings is common on Android: Chrome, Twidere & WhatsApp do this.

The available space in context menus is scare and i do not want to 'waste' it for seldom (but still quickly accessible) stuff.

**Comment by aminb** [comment]
Fair point. I guess I thought after removing the extraneous 'Now Playing' (and later on 'Show queue') item from menu we'd have room for 'About', but sure, we can keep it in Settings.

**Comment by xbao** [comment]
I agree with @adrian-bl, this shouldn't take up menu space for release users. A link in the about page will do the trick. Thanks, closing the PR

**Pull request closed without merging**
