### PR TITLE
Added button Get it on F-Droid

### PR DESCRIPTION
**Pull request by PanderMusubi**

### CODE REVIEW

**Comment by PanderMusubi** [comment]
Perhaps remove fdfilter=tinfoil& from the url if you want to.

**Comment by xbao** [comment]
Thanks for this, I think it's a good idea. What do you think about fetching the image from a URL rather than adding it as an image to the repo? Keep's the repo a little cleaner.

**Comment by PanderMusubi** [comment]
That's fine too. However I do not know where ks a good one. This one is from Wikipedia and might change jf people decided there to change it.

Perhaps a page on the wiki of F-Droid could be creates with instructions. I will make an issue for it at F-Droid. Probably will take some time so adding the image for now is the most practical. 

When wiki has instructions how to optimise this, I will ket you know. Ok?

**Comment by aminb** [comment]
@PanderMusubi Thanks for the PR!

However, I'd prefer to keep binaries (which include images) out of the repo history to keep it clean as much as possible, like @xbao said.

I'd opened https://github.com/gabrielelucci/greyscale-cmte/pull/7 for another project a few weeks ago, sourcing an image that's already hosted on F-Droid's servers. Should be OK to use that one.

**Comment by adrian-bl** [comment]
Note that syncthing.net also 'hotlinks' to the image hosted on f-droid (and they create far more traffic than we do with our github page), so i assume that the f-droid people don't care.

As an alternative, we could host the image on the nightly-build server

**Comment by PanderMusubi** [comment]
What do you think of this? https://gitlab.com/fdroid/fdroidserver/issues/168

**Comment by adrian-bl** [comment]
@PanderMusubi Many thanks for your PR: I'm closing this now as i've copy'n'pasted your changes into the README file while changing the URL of the image to 'http://neo01.eqmx.net/android/get_it_on_f-droid.png' (This is a VPS i own and is already used for nightly builds).

If F-Droid comes up with some 'official' markup & image URLs, i'd be happy to switch :-)

**Comment by PanderMusubi** [comment]
I asked F-Droid for an official line to be added to markdown in README.md but that triggered a huge discussion. Luckily this is slowly finding a prober solution and will let you know when they have one, or simply make a pull request.

**Pull request closed without merging**
