### PR TITLE
Display durations in albums tab

### PR DESCRIPTION
**Pull request by tobyhs**
This addresses https://github.com/vanilla-music/vanilla/issues/647#issuecomment-419882367

### CODE REVIEW

**Comment by andiandi13** [comment]
Thank you very very much !

**Comment by adrian-bl** [comment]
Thanks a lot: i'm just slightly worried whether or not this causes a performance degradation (due to the left join).

...but the additional work should be simple for sqlite to do: so let's merge it for now :-)

**Comment by adrian-bl** [comment]
Thanks a lot: i'm just slightly worried whether or not this causes a performance degradation (due to the left join).

...but the additional work should be simple for sqlite to do: so let's merge it for now :-)

**Comment by adrian-bl** [comment]
Thanks a lot: i'm just slightly worried whether or not this causes a performance degradation (due to the left join).

...but the additional work should be simple for sqlite to do: so let's merge it for now :-)

**Comment by adrian-bl** [comment]
Thanks a lot: i'm just slightly worried whether or not this causes a performance degradation (due to the left join).

...but the additional work should be simple for sqlite to do: so let's merge it for now :-)

**Comment by adrian-bl** [comment]
(deleted 3 comments - thank you github outage)

**Pull request merged**
