### PR TITLE
Modification in some issues 

### PR DESCRIPTION
**Pull request by Kaltrina31**
We have participated in the hackathon held in Prizren Kosovo, so during this activity we have worked in the project created by you.

### CODE REVIEW

**Comment by adrian-bl** [comment]
Are you sure that the PR is correct?
It only contains two commits of myself from a different branch.

**Comment by adrian-bl** [comment]
Closing this due to lack of reply.

**Comment by Kaltrina31** [comment]
Hi Adrian,

We have worked for three days, and we have tested many times in

many phones, we worked like a team.

until we worked everything was ok.

Please inform me if you accepted our pull request.

Best regards Kaltrina !


________________________________

**Comment by adrian-bl** [comment]
Please review your pull request: the request you sent does not include any commits of you: maybe you forgot to push your changes or did work on an incorrect branch?

**Comment by Kaltrina31** [comment]
ok I will do commit again and we will see the result.

best wishes Kaltrina !


________________________________

**Comment by dpocock** [comment]
@Kaltrina31 did you manage to find your commits?  Please feel free to ask if you need help with finding the branch in Git.  Do any of your team mates have a copy of the branch too, can you post the links to them?

**Pull request closed without merging**
