### PR TITLE
Add Vietnamese translation

### PR DESCRIPTION
**Pull request by abn-volk**
Hello! I've added the Vietnamese translation. I wonder if there are any Vietnamese speakers who use this app (I'm not one of them because my phone language is French :laughing:)... I'm new to Git so bear with me if there's any problem.

### CODE REVIEW

**Comment by adrian-bl** [comment]
Hi @abn-volk , many thanks for the translation. I merged your pull request.

However: We usually use transifex to translate Vanilla Music into different languages (https://www.transifex.com/vanilla_music/vanilla-music-1/)

Transifex makes it easy to spot + translate new strings.
I'll check if there is a way to import your translation into transifex. This would make updates to the translation much simpler.

**Comment by adrian-bl** [comment]
I was able to import your translation into transifex:
https://www.transifex.com/vanilla_music/vanilla-music-1/language/vi/
So if you would like to do any updates: Please create a transifex account, request to join the 'vi' translation and update the translation in the webinterface.

Oh: Btw: Transifex refused the plural-translations as it thinks that vietnamese only has one plural form. Is this correct?

**Comment by abn-volk** [comment]
Oh hi, sorry about the delay - I'm not very active on GitHub. I just requested to join the Vietnamese team.
I didn't quite get what you said there, but in Vietnamese, grammatical plurality is not really a thing. So for example, 1 apple and 2 apples are "1 quả táo" and "2 quả táo" - the noun stays the same. However, there are plural particle like những and các and they are required in some cases.

**Comment by adrian-bl** [comment]
> I didn't quite get what you said there, but in Vietnamese, grammatical plurality is not really a thing.

Ok, so then Transifex was correct:
Transifex rejected the translated plurals in the XML file because it 'knows' that Vietnamese translations should only have one translation for plurals. At the same time, Transifex would reject a german translation with less (or more) than 2 plurals or a polnish with != 3 plurals.

NB: I added you as a translator on transifex a few minutes ago

**Pull request merged**
