### PR TITLE
Make launcher icon more material

### PR DESCRIPTION
**Pull request by relan**
Current and renewed:

icon icon

Among other icons:

screenshot_20160522-160955

This is actually an RFC. I love current Vanilla icon, I think it needs a slight [material](http://www.google.com/design/spec/style/icons.html#icons-product-icons) refresh.

### CODE REVIEW

**Comment by adrian-bl** [comment]
Hi @relan , thanks a lot for the pull request.

I like the updated icon: @aminb @xbao , what do you guys think?

**Comment by aminb** [comment]
@relan Kudos! Looks beautiful.

@adrian-bl :+1: from me.

**Comment by adrian-bl** [comment]
ok, so in this case let's merge this :-)

**Comment by relan** [comment]
I've also made a new icon for the Headphones detector. Please see [this PR](https://github.com/vanilla-music/vanilla-headphone-detector/pull/5).

**Comment by adrian-bl** [comment]
:+1: thanks a lot! :-)

Would you like to be added to the About -> Contributors section?
If yes: what name should we use?

**Comment by relan** [comment]
> Would you like to be added to the About -> Contributors section?

I'd be very pleased! My real name is Andrew Nayenko.

**Comment by adrian-bl** [comment]
Great: i added you in commit af3f04e9e0448e709dd7b41b8578b61a0f587f6f

**Comment by ToNIX-** [comment]
Looks really good guys!

**Pull request merged**
