### PR TITLE
Implement share action in Library & NowPlaying

### PR DESCRIPTION
**Pull request by Adonai**
Part of #240

### CODE REVIEW

**Comment by aminb** [comment]
@Adonai Thanks for the PR!

Though sharing has been brought up a number of times in the past and was declined, I've been feeling the need recently (to send a track via email for example) quite a few times and I think this is a nice addition. It'd prefer to have a simple and standard sharing option in Vanilla than having to use whatever shitty browse dialog the destination app offers (if any).

Let's see if @adrian-bl has changed his mind about sharing, but I tested this my phone and looks good to me, and I'd like to see it merged.

**Comment by Adonai** [comment]
@aminb , thanks!
Didn't know there was discussion about it, hope Adrian is kind :)

**Comment by adrian-bl** [comment]
I'm not concerned about the feature itself, i'm just concerned about the space it takes up in the UI :-)

The Context-Menu in the library view is already very cramped - so how about adding this only to the FullPlaybackActivity's Menu? (Where we still have some space left)

**Comment by Adonai** [comment]
But what if I want to find a specific song via search box and just send it, not play?

P.. we may add submenus to library pop-up menu to shrink it.

**Comment by adrian-bl** [comment]
> P.. we may add submenus to library pop-up menu to shrink it.

Which options would you put in the sub menu? IMO, we only could create a submenu for 'More from...', and this would only save one entry

**Comment by Adonai** [comment]
Also:
Enqueue -> Next, Last
Play -> This, All
Actions -> Share, Delete [+Edit ID3 tag that I'm implementing currently]

**Comment by adrian-bl** [comment]
I'd really like to keep the Library-Context-Menu simple for now and only add this to the 'Now playing screen' - at least for now.

> Actions -> Share, Delete [+Edit ID3 tag that I'm implementing currently]

How would this work? Would it edit the MediaDatabase or the file itself?

**Comment by Adonai** [comment]
Ok, I'll remove it from library screen once I'm home.

> How would this work? Would it edit the MediaDatabase or the file itself?

The file itself, then run media scan for it

**Comment by adrian-bl** [comment]
> The file itself, then run media scan for it

I do not think that we should add this as this would be very confusing for the user:
Android supports many other formats apart from MP3, so it would be rather confusing for an user to be only able to edit certain files

**Comment by Adonai** [comment]
Why not add tag edit for those formats too. I'll show you once it's done. It's pretty meditative atm.

**Comment by adrian-bl** [comment]
Because i do not want to blow up the application by adding multiple dependencies (ID3v2, Ogg, Flac, MP4 tag writer) into Vanilla Music.

**Comment by Adonai** [comment]
@adrian-bl , why, I did it in 2011 with jaudiotagger. It had support for ogg, mp3, flac already and was just 834 kb. I had just wire up needed tags in needed files and wrap everything in a neat interface. Don't think it counts as bloat.

Anyways, I think it's topic of another discussion. I'll create an enhancement request soon, let's move there.

**Comment by Adonai** [comment]
Updated PR up against latest review comments

**Comment by adrian-bl** [comment]
Looks good to me, but cursor.close() is missing at line 537 in Media Utils - could you please update the pull request?

**Comment by Adonai** [comment]
Fixed by putting it in `finally` clause

**Comment by adrian-bl** [comment]
Thanks: Merged into master and fixed a crash bug via https://github.com/vanilla-music/vanilla/commit/ec985b24dffaefb887113dc76d4918db9d1a5121

**Pull request merged**
