### PR TITLE
Implement lyrics fetching using open LyricsWiki API

### PR DESCRIPTION
**Pull request by Adonai**
This PR adds new action for song list context menu

It creates a background activity to fetch lyrics page from LyricsWiki
and shows lyrics text of the song in the dialog

Future plans: 
- saving of lyrics to `USLT` tag (and retrieval)
- support for lyrics synchronization from `*.lrc` files

### CODE REVIEW

**Comment by adrian-bl** [comment]
Thanks for this PR, but unfortunately this will not get merged:

The patch requires Vanilla Music to have internet-access privileges which is something i'd like to avoid.
Also, it makes Vanilla Music dependent on a single 3th party service.

That said: I'm not against the idea of displaying lyrics in Vanilla Music (as requested in #302) but i think that downloading them would be done better in a seperated app:

Having a seperated app to do this (like the headphone detector) should be easy as we already broadcast the currently playing song.

**Comment by Adonai** [comment]
What's wrong with Internet access and Apache-licensed lib? Why avoiding it?

Besides, this is exactly the thing that has been requested in the only reddit thread of this player.

**Comment by Adonai** [comment]
Separate app would certainly contribute to Unix philosophy but I don't like the idea of switching between apps to do a very close related thing.

I plan on adding more features in the future and this PR is only beginning. I don't think that every feature I want would require a separate app, sorry.

If these are still unresolvable issues, are you OK with the idea of forking this into separate app in F-Droid?

**Comment by Adonai** [comment]
Oh, adrian, just noticed it's you.

Been using your player since 2011, great work.

**Comment by adrian-bl** [comment]
I was not talking about the json lib: I was talking about the LyricsWiki API (Which seems to get shutdown soon? -> (http://api.wikia.com/wiki/LyricWiki_API))

About the internet access: We are, foremost, a simple music player. Requesting internet access for such a niche feature just doesn't make much sense. (And *many* people like the fact that Vanilla Music does require so few permissions)

> Separate app would certainly contribute to Unix philosophy but I don't like the idea of switching 
> between apps to do a very close related thing.

The user would just have to have it installed: vanilla music and the lyrics-downloader could communicate via intents just fine (just like it's done with audio scrobblers)

**Comment by Adonai** [comment]
http://api.wikia.com/wiki/LyricWiki_API

This is hanging forever already, it was there when I started using it back into 2012.
Just the Lorem Ipsum to keep licensing issues away.

If this really shuts down, then I'm going to implement the interface in some other way.

**Comment by adrian-bl** [comment]
Vanilla Music is GPLv3 licensed, so you can build your own fork if you feel the need to do so. (But please change the icon & name to avoid confusion)

**Comment by Adonai** [comment]
You can close this PR then.
Anyways, it's extremely likely I'll be trying to upstream some non-intrusive changes, so seeing forward to work with you guys :)

**Comment by aminb** [comment]
@adrian-bl What do you think about implementing a simple plugin system for Vanilla, for situations like this?

We can have a simple plugin system and allow plugins to customize and/or add new behaviour in Vanilla.

This way,
- the core stays small,
- the feature that are not seen fit to be implemented in the original app can be added this way,
- no need to fork Vanilla or run a custom version for every little change, instead a plugin can be created that people can install/add to the app to make their desired functionality available / make the 'annoying' features gone.

I know it's not as simple as it sounds, but off top of my head, I know DashClock and Twidere have similar capabilities, and I think if we get it right it'll be quite something.

**Comment by adrian-bl** [comment]
> I know it's not as simple as it sounds, but off top of my head, I know DashClock and Twidere have similar 
> capabilities, and I think if we get it right it'll be quite something.

Yes, and Twideres Plugin System is simply using the standard android 'Intents' feature, which we already support (and is used by all widgets and the headphone detector app.)

To quote myself:
> > [...] The user would just have to have it installed: vanilla music and the lyrics-downloader could 
> > communicate via intents just fine (just like it's done with audio scrobblers)

I'm a big fan of intents and adding more of them to support various callbacks (eg: stuff like SONG_COVER_UPDATE, SONG_LYRICS_UPDATE, etc) is fine with me - and having a nicer twidere-like settings integration would also be fine for me.

> P.S. If you like the idea, I can open a new issue (RFC-like) to discuss it.

Yes, that might be a good idea - and a lyrics fetcher might also be a good prototype.
We could use QuickLyric (https://f-droid.org/repository/browse/?fdid=com.geecko.QuickLyric) as a testbed which already works nicely with vanilla music (by waiting for our broadcast events). All that's missing IMO would be some:
```
final Intent intent = new Intent(INTENT_VANILLA_DISPLAY_TEXT_ON_COVER);
intent.putExtra(VANILLA_EXTRA_TEXT, "These are the song lyrics....");
intent.putExtra(VANILLA_EXTRA_DURATION, 5000); // 5 sec
```
callback.

**Comment by adrian-bl** [comment]
@aminb @Adonai I created issue #304 as a 'placeholder' issue for the plugin system - feel free to comment

**Pull request closed without merging**
