### PR TITLE
426 material design icons

### PR DESCRIPTION
**Pull request by kgilmer**
I followed exactly PanderMusubi's specification in https://github.com/vanilla-music/vanilla/issues/426.

Here is a shell script I wrote to make it a little quicker (res_update.sh):

```
#!/bin/bash

SRC_DIR=$1
SRC_RES_FILENAME=$2
DST_DIR=$3
DST_RES_FILENAME=$4

if [ $# -eq 0 ]
then
    echo "No arguments supplied"
    exit
fi

array=( drawable-hdpi drawable-mdpi drawable-xhdpi drawable-xxhdpi drawable-xxxhdpi )
for i in "${array[@]}"
do
  SOURCE=$SRC_DIR/$i/$SRC_RES_FILENAME
  TARGET=$DST_DIR/$i/$DST_RES_FILENAME
  if [[ ! -f $SOURCE ]] ; then
      echo $SOURCE doesnt exist
      exit
  fi
  if [[ ! -f $TARGET ]] ; then
      echo $TARGET doesnt exist
      # exit
  fi

  cp -v $SOURCE $TARGET
done

```

~~~~

here is my terminal history of command operations:

 ```
 556  ./res_update.sh /Users/kgilmer/Downloads/ic_skip_previous_white_24dp/android ic_skip_previous_white_24d.png ./res previous.png
  558  ./res_update.sh /Users/kgilmer/Downloads/ic_skip_previous_white_24dp/android ic_skip_previous_white_24dp.png ./res previous.png
  559  ./res_update.sh /Users/kgilmer/Downloads/ic_skip_previous_white_24dp/android ic_skip_previous_white_24dp.png ./res widget_previous.png
  561  ./res_update.sh /Users/kgilmer/Downloads/ic_play_arrow_white_24dp/android ic_play_arrow_white_24dp.png ./res widget_play.png
  562  ./res_update.sh /Users/kgilmer/Downloads/ic_play_arrow_white_24dp/android ic_play_arrow_white_24dp.png ./res play.png
  563  ./res_update.sh /Users/kgilmer/Downloads/ic_pause_white_24dp/android ic_pause_white_24dp.png ./res pause.png
  564  ./res_update.sh /Users/kgilmer/Downloads/ic_pause_white_24dp/android ic_pause_white_24dp.png ./res widget_pause.png
  565  ./res_update.sh /Users/kgilmer/Downloads/ic_skip_previous_white_24dp/android ic_skip_previous_white_24dp.png ./res previous.png
  566  ./res_update.sh /Users/kgilmer/Downloads/ic_skip_previous_white_24dp/android ic_skip_previous_white_24dp.png ./res widget_previous.png
  567  ./res_update.sh /Users/kgilmer/Downloads/ic_play_arrow_white_24dp/android ic_play_arrow_white_24dp.png ./res play.png
  568  ./res_update.sh /Users/kgilmer/Downloads/ic_play_arrow_white_24dp/android ic_play_arrow_white_24dp.png ./res widget_play.png
  569  ./res_update.sh /Users/kgilmer/Downloads/ic_pause_white_24dp/android ic_pause_white_24dp.png ./res widget_pause.png
  570  ./res_update.sh /Users/kgilmer/Downloads/ic_pause_white_24dp/android ic_pause_white_24dp.png ./res pause.png
  572  ./res_update.sh /Users/kgilmer/Downloads/ic_skip_next_white_24dp/android ic_skip_next_white_24dp.png ./res next.png
  573  ./res_update.sh /Users/kgilmer/Downloads/ic_skip_next_white_24dp/android ic_skip_next_white_24dp.png ./res widget_next.png
  574  ./res_update.sh /Users/kgilmer/Downloads/ic_repeat_white_24dp/android ic_repeat_white_24dp.png ./res repeat_active.png
  575  ./res_update.sh /Users/kgilmer/Downloads/ic_repeat_white_24dp/android ic_repeat_white_24dp.png ./res repeat_inactive_service.png
  576  ./res_update.sh /Users/kgilmer/Downloads/ic_repeat_white_24dp/android ic_repeat_white_24dp.png ./res repeat_inactive.png
  577  ./res_update.sh /Users/kgilmer/Downloads/ic_repeat_one_white_24dp/android ic_repeat_one_white_24dp.png ./res repeat_current_active.png
  578  ./res_update.sh /Users/kgilmer/Downloads/ic_looks_one_white_24dp/android ic_looks_one_white_24dp.png ./res stop_current_active.png
  579  ./res_update.sh /Users/kgilmer/Downloads/ic_search_white_24dp/android ic_search_white_24dp.png ./res ic_menu_search_material.png
  580  ./res_update.sh /Users/kgilmer/Downloads/ic_search_white_24dp/android ic_search_white_24dp.png ./res ic_menu_search_holo.png
  581  ./res_update.sh /Users/kgilmer/Downloads/ic_more_vert_white_24dp/android ic_more_vert_white_24dp.png ./res ic_menu_moreoverflow_normal_holo_dark.png
  582  ./res_update.sh /Users/kgilmer/Downloads/ic_reorder_white_24dp/android ic_reorder_white_24dp.png ./res grabber.png
  583  ./res_update.sh /Users/kgilmer/Downloads/ic_star_white_24dp/android ic_star_white_24dp.png ./res btn_rating_star_on_mtrl_alpha.png
  584  ./res_update.sh /Users/kgilmer/Downloads/ic_casino_white_24dp/android ic_casino_white_24dp.png ./res random_active.png
  585  ./res_update.sh /Users/kgilmer/Downloads/ic_star_border_white_24dp/android ic_star_border_white_24dp.png ./res btn_rating_star_off_mtrl_alpha.png
  586  ./res_update.sh /Users/kgilmer/Downloads/ic_folder_white_24dp/android ic_folder_white_24dp.png ./res folder.png
  587  ./res_update.sh /Users/kgilmer/Downloads/ic_keyboard_arrow_right_white_24dp/android ic_keyboard_arrow_right_white_24dp.png ./res arrow.png
  588  ./res_update.sh /Users/kgilmer/Downloads/ic_close_white_24dp/android ic_close_white_24dp.png ./res notification_close_dark.png
  589  ./res_update.sh /Users/kgilmer/Downloads/ic_close_white_24dp/android ic_close_white_24dp.png ./res notification_close.png
  590  ./res_update.sh /Users/kgilmer/Downloads/ic_music_note_white_24dp/android ic_music_note_white_24dp.png ./res ic_musicnote.png
  591  ./res_update.sh /Users/kgilmer/Downloads/ic_album_white_24dp/android ic_album_white_24dp.png ./res ic_disk.png
  592  ./res_update.sh /Users/kgilmer/Downloads/ic_person_white_24dp/android ic_person_white_24dp.png ./res ic_microphone.png
  593  ./res_update.sh /Users/kgilmer/Downloads/ic_shuffle_white_24dp/android ic_shuffle_white_24dp.png ./res shuffle_inactive_service.png
  594  ./res_update.sh /Users/kgilmer/Downloads/ic_shuffle_white_24dp/android ic_shuffle_white_24dp.png ./res shuffle_inactive.png
  595  ./res_update.sh /Users/kgilmer/Downloads/ic_shuffle_white_24dp/android ic_shuffle_white_24dp.png ./res shuffle_active.png
  596  ./res_update.sh /Users/kgilmer/Downloads/ic_album_white_24dp/android ic_album_white_24dp.png ./res shuffle_album_active.png
```

### CODE REVIEW

**Comment by kgilmer** [comment]
Upon testing, it looks like the 'Files' icon needs the black treatment instead of the white.

**Comment by adrian-bl** [comment]
Thats not how we roll: drawables are ALWAYS created from SVGs: generate-pngs.sh takes care of doing this correctly.

Also note that i am not such a big fan of the material stock icons.

**Comment by kgilmer** [comment]
Regarding "drawables are ALWAYS created from SVGs": where is the developer guide with all these rules I have yet to read?

**Comment by Adonai** [comment]
@adrian-bl , Vanilla does look like an old style player now, honestly. Material icons are the proposed way forward, all 5.x-7.x ecosystem is built on them. I have seen lots of requests both on Telegram FLOSS chats and reddit about them in Vanilla, this has quite a weight.

P.S. Low-hanging fruits should remain low-hanging, tbh. Custom steps, "stock" vs "non-stock" and undocumented build steps are our own fault. Perl scripts to make themes work? Generating icons from SVGs? Building with Ant instead of Gradle? Declining plugins without ContentResolver calls then wiping these calls all off from player completely? I bet we lose traction with such attitude.

**Comment by adrian-bl** [comment]
There is no developer guide (we are a small project), but a quick search in the git history for 'icon' will lead you to commits like these:

https://github.com/vanilla-music/vanilla/commit/294a6706071856796aed096871ec2222d4e942c7

Also note that your sizes are off: mdpi icons should have a base of 48x48px.

@Adonai 

> undocumented build steps are our own fault.

We surely could add some documentation - or improve the build system. (Also note that generage-pngs.sh pre-dates myself).

> Perl scripts to make themes work? 

The script is just used to generate some XML files - what would your suggestion be?

> Declining plugins without ContentResolver calls then wiping these calls all off from player completely?

We still interact with the native media db. My point back then was that we could use androids native 'subsystem' to pass media items around. This was before i started the whole media-db thing.

**Comment by Adonai** [comment]
@adrian-bl ,

> We surely could add some documentation - or improve the build system. (Also note that generage-pngs.sh pre-dates myself).

Didn't know that.

> The script is just used to generate some XML files - what would your suggestion be?

It'd be good if we could include this in build process to re-generate these files automatically.

Just worried of project health. Sorry.

**Comment by Adonai** [comment]
@kgilmer , also, are you sure white icons won't be illegible in some themes?

**Comment by kgilmer** [comment]
Hi @Adonai , it could very well be.  I found one icon in testing that clearly won't work in the stock: the Folder icon.  There may be others.  I had assumed that @PanderMusubi's selections were sufficient but seems like there is more work which is fine.  I will need to take a look at the generate-pngs.sh script tonight to get a better understanding of the build system.

**Comment by adrian-bl** [comment]
> Just worried of project health. Sorry.

That's a good thing to worry about :-)

About the build system: I agree that it could use some improvements.
I do not like ant but i REALLY hate gradle - i'm not touching this - ever.

IMO, using Bazel (https://bazel.build) and ditching both ant and gradle would be a blessing - but this will probably confuse many people and might break f-droid builds.

But: How about something simple as a makefile? The makefile would refresh icons + themes and then run ant / gradle ?

This would make building the project pretty easy. But in any case: we should move the discussion into a seperated issue.

**Comment by Adonai** [comment]
Sounds like good idea, but Windows OS users may be confused with Makefile...

I'll try to come up with something. At the very worst scenario I can re-implement it in groovy script and then call it from ant/gradle.

> i REALLY hate gradle - i'm not touching this - ever.

I know this feel :-) I hope Android Studio along with its IntelliJ ancestor will jump on another train someday.

**Comment by kirbyfan64** [comment]
> IMO, using Bazel (https://bazel.build) and ditching both ant and gradle would be a blessing - but this will probably confuse many people and might break f-droid builds.

[*cough*](https://buckbuild.com/) [*cough*](https://github.com/uber/okbuck)

**Comment by kgilmer** [comment]
My dev environment is not compatible with the vanilla build scripts.  I'm unable to complete this task as required by project maintainers.  Closing PR.

**Pull request closed without merging**
