### PR TITLE
Switch build system from Eclipse/ANT to Android Studio/Gradle (#152)

### PR DESCRIPTION
**Pull request by AltNico**
Changes I made:
- changed .gitignore
- edited README.md
- moved versionCode and versionName from AndroidManifest.xml to app/build.gradle
- corrected locations in generate-pngs.sh and in update-translations.py

Info: The sources are now in app/src/main .
I dropped support for ANT because it would require an additional script, I think.

### CODE REVIEW

**Comment by aminb** [comment]
Thanks for the PR, but couldn't we preserve the project structure and just add the needed Gradle files? As far as I know, we can specify custom paths for the manifest and `src` and `res` directories.

**Comment by AltNico** [comment]
@aminb See my latest commits, I moved back to the old project structure. It now has ANT support, I think.

**Comment by adrian-bl** [comment]
Thanks for the PR: Looks good to me - i'll give it a try and merge if it works fine for me

Btw: Is there a reason on why you touched the translatable.xml files? They are auto-generated by transifex

**Comment by AltNico** [comment]
If you follow my commits you see I first imported the project into Android Studio which changed the project structure. In this process Android Studio edited the files, I do not know why.

I will delete the senseless commits and push one new commit where I just add the gradle and gitignore file, so please wait before you merge this.

**Pull request closed without merging**
