### PR TITLE
Reformat code using Android Studio

### PR DESCRIPTION
**Pull request by AltNico**
I know this are a lot of changes and because of this I put it in a separate branch.
Here I did reformat the whole code using Android Studio's build-in funtion.

### CODE REVIEW

**Comment by aminb** [comment]
@AltNico Thank you for your effort. I've been very busy the last couple of days, and won't have much free time during the weekend either. I'll have more free time after Monday.

So, what sort of "reformatting" has the Android Studio done? Does the new code follow the project coding style? One of the things I notice is that it's changed tabs to spaces, but in Vanilla tabs are the preferred one.

If the only difference between this PR and #154 is the code reformatting, I think we'll be merging the other one (for build system changes) and skip the reformatting.

@adrian-bl

**Comment by adrian-bl** [comment]
This patch would mess up the whole project history (git blame ....) and tabs ARE the standard in Vanilla Musics code base.

We could argue about the inconsistent use of curly brackets in function definitions (Same line / next line) - but tabs are here to stay ;-)

**Comment by AltNico** [comment]
@aminb Android Studio "rearrange entries" and "optimize imports" when you call the function. I do not know, which scheme it follows when it does that but code looks better after that IMO.

@adrian-bl I understand that you do not want to merge this and because of this I put it in a separate branch, I just wanted to give you the possibility.

**Comment by aminb** [comment]
@AltNico To be honest if I had a saying, along other things I'd say we went with spaces, but the code base is quite big and it's been like this since forever, so let's keep it consistent as it is, and as Adrian mentioned not mess up the git history haha.

Thanks again.

**Pull request closed without merging**
