### PR TITLE
add "Empty queue" option in Queue activity

### PR DESCRIPTION
**Pull request by aminb**
TODO @adrian-bl :

- `empty_queue` string already exists (should be renamed probably)
- `clear_queue` should be renamed to `dequeue_rest` and changed to "Dequeue rest"

### CODE REVIEW

**Comment by adrian-bl** [comment]
Looks good to me apart from the fact that it should also call
 			mCallback.activeSongReplaced(-1, getSong(-1));
as the previous song in the timeline also changed.

That said: Both emptyQueue() and clearQueue() should probably use the 'saveActiveSongs(), broadcastChangedSongs(), changed()' triple instead of fiddling with mCallback directly.

**Comment by aminb** [comment]
Done.

How can I update the Now Playing screen to show the "empty queue" overlay after I call `emptyQueue`? I looked up a couple files and saw the `onStateChanged` and `setState` methods, but not sure how to correctly trigger a state change (after emptying the whole queue).

**Comment by adrian-bl** [comment]
Hmm, it should switch into this state automatically, but the emptyQueue function also needs to call mCurrentPos = 0; before calling the broadcast function - otherwise we would mess up the internal timeline state.

....vanillas Timeline class is a scary beast ;-)

**Comment by adrian-bl** [comment]
I'm merging this: i just tested it and the 'empty queue' screen shows up correctly on my device.

**Comment by aminb** [comment]
Awesome.

Yeah the Timeline class is quite a beast :)

**Pull request merged**
