### PR TITLE
Custom drawn playback icons

### PR DESCRIPTION
**Pull request by reactorcoremeltdown**
These icons bring the Sony Walkman aesthetics to Vanilla Music, however these are made from 100% original vector assets that are also a part of this update.

image

Disclaimer: it has been reported that the icons might look inconsistent on some Android flavours. I have only tested this on stock versions of Android 11 and 12.

Please feel free to close the pull request if it does not meet any of the requirements.

### CODE REVIEW

**Comment by reactorcoremeltdown** [comment]
Yikes, seems like I forgot to update widget preview pictures.

**Comment by adrian-bl** [comment]
Thanks! Did you generate the PNG files using a program or were they re-generated using the shell script? (which calls inkscape)

**Comment by reactorcoremeltdown** [comment]
> Thanks! Did you generate the PNG files using a program or were they re-generated using the shell script? (which calls inkscape)

I generated icons by running Inkscape wrapper from this repo on my WSL box.

**Comment by adrian-bl** [comment]
Cool, thanks!

But i noticed that the play button has a strange background: is that intentional?

image

**Comment by adrian-bl** [comment]
Hmm... seems that's not an issue with the PNG file, but that we are doing something to the play button. Let me dig in

**Pull request merged**
