### PR TITLE
static analysis fixes

### PR DESCRIPTION
**Pull request by xbao**
No functionality changes. Changes informed by lint/Android Studio static analysis errors.

### CODE REVIEW

**Comment by adrian-bl** [comment]
Thanks for your pull request.
But the pull request also modifies the DSLV project which is just a copy of https://github.com/bauerca/drag-sort-listview/tree/master/library - i'd rather not touch this copy as it would make merges in the future much more complicated.

Could you update the pull request to exclude any changes to DSLV?

**Comment by xbao** [comment]
Hmm, I emailed a reply a while ago but I guess the internet ate it. 

Yeah no worries, I'll let you know when it's updated

**Comment by xbao** [comment]
Sweet, the changes in the DSLV source were all JavaDoc fixes anyway. Updated the PR

**Comment by adrian-bl** [comment]
Hi @xbao , thanks a lot for the updated PR - i merged it into the master.

**Pull request merged**
