### PR TITLE
Implement import/export of settings (#222)

### PR DESCRIPTION
**Pull request by xbao**
File is hard-coded to ~~`/sdcard/vanilla_preferences`~~ `/sdcard/vanilla_settings`

Known issue: if the user goes to a child preference screen (e.g. 'Audio') then imports saved preferences from there, the preferences still have the old values when returned to. 

Questions/comments/concerns?

### CODE REVIEW

**Comment by okungnyo** [comment]
Minor quibble, but shouldn't it be 'Settings', not 'Preferences'?

'Settings' seems to be the standard language in Android.

**Comment by adrian-bl** [comment]
Looks ok to me, but please change the license boilerplate to use your own name + the GPLv3 (See eg. ShowQueueActivity.java)

Chris Eby licensed his code under the MIT license, but i'm using the GPLv3 for all new code to (hopefully) limit the number of fake-closed-source-only-clones of VanillaMusic in the Play Store

**Comment by okungnyo** [comment]
Can you link some of them?

I want to see what kind of clones to watch out for.

**Comment by adrian-bl** [comment]
I think that most of them vanished from the playstore in the meantime - but searching for 'flac gapless' used to show at least 5 clones (they also did a 1:1 copy of the screenshots + description)

**Comment by kirbyfan64** [comment]
@adrian-bl Unfortunately, they're still not all gone. iMusic player looks exactly like pre-Material Vanilla, and NexGen player looks pretty close.

I thought the MIT license required the original notice to always be present:

 > The above copyright notice and this permission notice shall be included in
all copies or substantial portions of the Software.

So those guys are probably violating the license anyway...

**Comment by xbao** [comment]
@okungnyo yip, you're right. The Android API calls them preferences, but it's probably a good idea to call them Settings everywhere else rather than mix the two.

@adrian-bl Doh, sure thing. As you probably guessed, I copy pasted without looking at it. 

I'll update on the weekend

**Comment by adrian-bl** [comment]
No need to hurry: I'll be mostly offline in the next 3 weeks anyway.

Btw: The patch adds a new options-menu to the preferences activity to start the export/import dialog.
How about moving it into the 'Misc Features' section (+ get rid of the options menu) or would this hide the feature too much?

**Comment by okungnyo** [comment]
So will Preferences be renamed to Settings?

**Comment by xbao** [comment]
@adrian-bl I was 50/50 between adding it to misc and having it as a menu option. I'll add it to misc. 

I also just realised that the icon isn't compatibly licensed. I bought the LinearIcons pack on icomoon.io which claimed it was 'permissively licensed', but in reality has a huge amount of restrictions about weird things like the number of developers that work on the project. There's a free version of the icon which is licensed under CC BY-SA 4.0, which is compatible with the GPLv3, but adding a new license to the project just for the icon next to the file name doesn't seem worth it.


@okungnyo Yip, the file will be renamed `vanilla_settings`.

**Comment by xbao** [comment]
Coolio, changes made. I may also be AFK for a couple of weeks, so not fussed about time.

**Comment by okungnyo** [comment]
So Preferences has been renamed to Settings *everywhere* in the app?

**Comment by xbao** [comment]
@okungnyo Nope, that's outside the scope of the issue this PR is implementing. Not sure if that's a good idea for the internal classes anyway, as they extend from/use the Android classes which (mostly) use `Preferences`. Regardless, I would suggest you chuck it up in an issue for discussion if you feel it should be changed.

**Comment by okungnyo** [comment]
OK: #250

**Comment by adrian-bl** [comment]
@xbao about the icon:

I've used http://publicdomainvectors.org in the past. They have a pretty good library of cc0/pd icons

**Comment by okungnyo** [comment]
Yes, please change the icon! The current one looks makes it look like a Chinese clone, when it's the furthest from it.

**Comment by xbao** [comment]
I'm back where I belong (at the keyboard) and I'm picking this up again. I've removed the icon. Currently trying to get the miscellaneous preferences screen to update itself if the the settings are restored from the file. It's turning out to be painful, and will probably end up requiring a small amount of hackery

**Comment by xbao** [comment]
Changes are pushed. If anybody is interested in testing it an APK with the changes can be found at https://github.com/xbao/vanilla/releases/download/1.0.35.beta/vanilla-1.0.35.beta.afb87d0.debug.apk 

A couple of things:

1. Doesn't look so good. Figured we'll get the desired functionality figured out first, rather than prettify stuff that will just be thrown out.
2. I've duplicated ~4 lines of code in the methods `postFinish`. I thought about moving them out to an `ActivityUtil` class but wasn't sure if it was worth the extra complexity/indirection for such a trivial piece of code

Feedback, as always, is most welcome

**Comment by xbao** [comment]
Just realised there were a couple of drawable copies I forgot to remove. They don't cause any programmatic issues, just licensing ones. Removed in commit 4fcbc28.

**Comment by adrian-bl** [comment]
Looks pretty ok for me - but do you know why github shows some old changes (eg. viewpager) in the pull request diff: https://github.com/vanilla-music/vanilla/pull/246/files is this normal?

@xbao Could you please add some comments (the normal function boilerplate) to the settings importer/exporter java file? Please also remove the debug-logs.
How robust is the import/export mechanism with new/unknown and missing keys?

**Comment by xbao** [comment]
> do you know why github shows some old changes (eg. viewpager)...

That's bizarre, I have no idea. It looks like there are three commits that I somehow added to the branch. I'll revert the commits or rebase & force push, do you prefer one over the other?

> Could you please add some comments (the normal function boilerplate) to the settings importer/exporter java file? 

Yip, will do.

> Please also remove the debug-logs.

Yip, no problem. Just out of curiosity, is there a reason you don't want to strip them with proguard? 

> How robust is the import/export mechanism with new/unknown and missing keys?

Hmm, very good question, I'm not sure. I'll find out

**Comment by xbao** [comment]
Closing the PR, I'll re-open when it's fixed up

**Comment by xbao** [comment]
Having another look, I think the 'Up to date?' copy, which indicates if the contents of the file is the same as the current users settings, might be confusing. It kind of makes it sound like something needs to be updated.

vanilla_importexport_status_nofile vanilla_importexport_status_fileinsync vanilla_importexport_status_fileoutofdate

Thoughts/suggestions?

**Comment by aminb** [comment]
@xbao How about something along the lines of

- *Backup settings match current app settings*, in which case we would disable the export button,

- *Backup settings __don't__ match current app settings*, in which case we would leave both buttons enabled,

- *File doesn't exist*, in which case we would disable the import button.

**Comment by xbao** [comment]
@aminb Nice, I will do that

**Comment by aminb** [comment]
@xbao Looking forward to it :)

**Comment by xbao** [comment]
Changes since last PR:

* Buttons enable/disable based on the backup file and whether the current settings differ (thanks @aminb) 
* Renamed (both code and user-facing text) from import/export to restore/backup. I found myself getting confused about which button did what, which is never a good sign.
* Added a dialog asking for confirmation for overwriting the existing backup file (for a backup) or the current app settings (for a restore)
* Refactored the Activity code for clarity and to remove duplicated logic
* Added more JavaDoc
* Added a file icon (from the free set of icomoon.io, licensed under GPL)

> How robust is the import/export mechanism with new/unknown and missing keys?

@adrian-bl Just realised I didn't answer this question. A summary of the backup logic:

1. Get all <key,value> pairs from the SharedPreferences object
2. Write these out to the file

And of the restore (whole thing done atomically through the SharedPreferences.Editor):

1. Clear the preferences
2. Read <key,value> pairs
3. Add each pair into the preferences

So for new keys (such as if a preference is added), if the user has 

* a backup of the old version's settings and
* modified some preference with a new key and
* restores the backup

the settings will no longer contain the new key, and so will use the default value. Effectively, it will throw out the changes the user made to the new key. Not good.

For unknown keys (such as if a preference is removed), the restore will put them into the SharedPreferences object, but they'll never be accessed so they won't affect behaviour. Still not ideal. 

For missing keys (as in missing from the backup file) the restore won't put them in the SharedPreferences, so the behaviour will be as if the user never modified them.

One solution for the new key issue is to change the restore logic to:

1. Read <key,value> pairs from the backup file
2. Add each pair to the current preferences, overwriting existing values

That will give us the union of the backup set and the current set, with precedence given to the backup entries where keys conflict. 

Another similar issue crops up if 

* User has an old backup
* an update to the app adds/changes a key to one that was used previously 

Then the app will interpret the old value as the value for the new setting. And if the re-used key has a different value type, I'm guessing it will crash when read. They're all things that should be avoided anyway, because a user might do a straight update from a very old version to the newest. But the backup/restore functionality increases the chance of those types of updates causing problems.

I dunno, the potential issues with this approach seem pretty unlikely, but still might not be worth the functionality?

Some dumps of the maps we're dealing with:

```
# Clean app backup (All from the Miscellaneous section, where the backup option is)
D/prefs[0]: enable_readahead->false
D/prefs[1]: library_page->0
D/prefs[2]: double_tap->false
D/prefs[3]: scrobble->true
D/prefs[4]: use_idle_timeout->false
D/prefs[5]: disable_lockscreen->false
D/prefs[6]: stock_broadcast->false

# Personal settings
D/prefs[0]: cover_longpress_action->Nothing
D/prefs[1]: swipe_down_action->SeekForward
D/prefs[2]: use_dark_theme->false
D/prefs[3]: cover_press_action->SeekBackward
D/prefs[4]: headset_pause->true
D/prefs[5]: headset_only->false
D/prefs[6]: visible_controls->true
D/prefs[7]: stock_broadcast->false
D/prefs[8]: library_whitelist->/storage/sdcard1/Music
D/prefs[9]: media_button_beep->true
D/prefs[11]: App Restrictions->AAAAAA==
                  
D/prefs[12]: library_page->4
D/prefs[13]: double_tap->false
D/prefs[14]: volume_during_ducking->56
D/prefs[15]: sort_2_-1->0
D/prefs[16]: swipe_up_action->ShowQueue
D/prefs[17]: media_button->true
D/prefs[18]: enable_readahead->false
D/prefs[19]: scrobble->true
D/prefs[20]: display_mode->2
D/prefs[21]: default_action_int->7
D/prefs[22]: use_idle_timeout->false
D/prefs[23]: disable_lockscreen->false
D/prefs[24]: bgsync_launch_next_online->false
D/prefs[25]: cycle_continuous_shuffling->false
D/prefs[26]: visible_extra_info->false
D/prefs[27]: playback_on_startup->false
D/prefs[28]: sort_1_-1->0
D/prefs[29]: default_playlist_action->3
```

**Pull request closed without merging**
