### PR TITLE
New theme: Start Wearing Purple

### PR DESCRIPTION
**Pull request by reactorcoremeltdown**
This is my humble attempt to add a new theme to the roster.

---

Notable features:

+ Named after a song of Gogol Bordello
+ Purple/violet/indigo colors out of a generated palette
+ Different background color to match theme
+ Fully transparent circle around play/pause button

Considerations:

+ Please feel free to reject if something doesn't fit, however I'd appreciate feedback if there is any
+ The `generate-themes.pl` script was not modified or used in any way, it would have required a significant rewrite to make use of it
+ I don't think I could help translating theme name into all other languages (except of maybe Russian), in my opinion it shouldn't be translated as it refers to a song name

### CODE REVIEW

**Comment by adrian-bl** [comment]
thanks, i love it!

i'll try to take a look at it next week

**Comment by adrian-bl** [comment]
Ok, that took MUCH longer than expected, but its finally in:

67e7c9ff6af00cec9aa21e65cb8dd51d2a77d644

I didn't merge this PR since i wanted 'generate-themes.pl' to continue working (which the commit does: it updates the script to generate the XML)

Let me know if i should add you (and how: real name, github handle?) to the in-app credits screen.

**Comment by reactorcoremeltdown** [comment]
Wow, thanks a lot!

Real name + github handle would be good: `Azer Abdullaev @reactorcoremeltdown`

**Comment by adrian-bl** [comment]
ok, done in ab3e28158046840874c1b18cdc5d99c6f697d5b5 - thanks again!

**Comment by andiandi13** [comment]
Purple theme is currently buggy on the nighty for me img

**Comment by adrian-bl** [comment]
Interesting... does that only happen with the new theme or others?
What Android version are you using?

**Comment by andiandi13** [comment]
@adrian-bl No only this purple theme, all other themes have always work fine.
I'm on Android 9

**Comment by adrian-bl** [comment]
Well, that is very very odd: the theme doesn't do anything special or different.

Did you try to reboot or reinstalling vanilla?

**Comment by adrian-bl** [comment]
Oh wow: i can reproduce this in the emulator. Amazing

**Comment by adrian-bl** [comment]
a182f603a486c029ede1c705033c7417b0a2ca88 seems to fix it. This makes absolutely no sense.. but well?

**Comment by andiandi13** [comment]
@adrian-bl Great ! It works perfectly now. img

Is this the intended render ? Because on the screenshots above I see rounded control icons.

Also @reactorcoremeltdown thank you for this amazing theme

**Comment by adrian-bl** [comment]
Ah, good catch regarding the icons - i don't see that included in @reactorcoremeltdown 's PR but i could add them if he publishes the graphics

**Comment by reactorcoremeltdown** [comment]
> Ah, good catch regarding the icons - i don't see that included in @reactorcoremeltdown 's PR but i could add them if he publishes the graphics

You're a wonderful bunch of people, that's what I have to say!

Sure, I will supply the icons in another PR once I recover from flu.

Thanks again you both!

**Comment by adrian-bl** [comment]
Great! And hope the flu isn't too bad and that you feel better soon!

**Pull request closed without merging**
