### PR TITLE
Created black theme

### PR DESCRIPTION
**Pull request by PiwwowPants**
Added a black theme option to the theme options under the Greyish.Dark theme. This will let OLED-based screens turn off their pixels on the black regions.

* Added black theme to list of themes
* Created the black theme
     * This theme depends on Greyish.Dark to inherit most of its duplicate entries. This adds the tech debt of forcing anyone changing Greyish.Dark to verify Black is okay
     * This theme overrides the PopupMenu background explicitly so it doesn't blend into the black backgrounds. This color matches the dialogs used elsewhere

### CODE REVIEW

**Comment by adrian-bl** [comment]
Thanks, but this won't work as expected:

* We currently expect an even number of themes where odd ones are dark:
https://github.com/vanilla-music/vanilla/blob/master/src/ch/blinkenlights/android/vanilla/ThemeHelper.java#L85
Nothing we can't fix with additional attributes - but the current change would mess up some themes.

* Also note that themes are auto-generated: The definition should go into 
https://github.com/vanilla-music/vanilla/blob/master/generate-themes.pl (as described in the header of the existing XML files).

**Comment by PiwwowPants** [comment]
* That is interesting. I was wondering why the theme was not being applied with dark settings. Another interesting thing is that after I renamed the theme Black.Dark in the style sheet, it started getting applied dark settings. Is there a reason for that, and if so, is it necessary to be performing that logic you noted?
If anything I can just put it last in the list. I just wanted to put it next to the Greyish.Dark theme.

* Gotchya. Sorry, I must have misunderstood. I thought it was just saying they WERE generated. I did not know I had to define it in that file. Thanks for the heads up on that.

**Comment by adrian-bl** [comment]
> I renamed the theme Black.Dark in the style sheet

Are you using ant? Ant is pretty good at messing up resources, so you might have seen some strange state.

> If anything I can just put it last in the list.

We probably still need some mechanism to mark it as black only: the current code expects (and generates) always a light and a dark version of each theme.

**Comment by PiwwowPants** [comment]
I am not using Ant but it's still possible something went weird. I can look into that. 

As for the mechanism for black only, I can look at that too to see if it's worth it if you would like the black theme still. I think the change would be arbitrary. Famous last words.

**Comment by adrian-bl** [comment]
Sure: i'd be happy to include a black theme

**Comment by PiwwowPants** [comment]
The black theme is not back to how it should look yet, but I pushed up some changes to make it so the app is not dependent on having both a dark and light theme for each theme type. It seems to work but I wanted to know what you think.

I don't know Perl very well, so critique me on that.

**Comment by adrian-bl** [comment]
Sorry for the delayed replay: i wasn't at a PC that often in the last few days.

I made some changes to how theming is done and creating a black-only theme is now possible - custom background colors can also be set.

I added the amoled theme using your color values in
https://github.com/vanilla-music/vanilla/commit/9149ea92b78d5b7ca31266e99b4350bba3c80c03

The change is already included in the latest nightly build - feel free to give it a try and report feedback!

**Comment by adrian-bl** [comment]
Closing this pull request: A Black theme is now in 1.0.59 (in Alpha and also soon on f-droid)

**Pull request closed without merging**
