### PR TITLE
Audio sharing ability.

### PR DESCRIPTION
**Pull request by NextLight**
Add share option to LibraryActivity (except for the File tab) and to
FullPlaybackActivity.
It can also share every song from an album, artist, etc.

### CODE REVIEW

**Comment by aminb** [comment]
Hi @NextLight,

I'm not sure why this has been unanswered for so long. I haven't checked the pull requests section in a really long time, and I should do that more often.

As for the actual pull request, thank you for submitting. However, if I recall correctly sharing came up at some point in the past and I think was dismissed by @adrian-bl as an effort to keep the app minimal and without *social* features.

Care to comment on this Adrian?

**Comment by adrian-bl** [comment]
I'm not a big fan of this feature:
Sharing features make sense for 'content creating' apps, such as a camera, voice recorder or a download manager (including browsers).

But we are a music player which will play back already stored files. If someone would like to share such a file, he could simply use one of the many filemanagers available for android.

**Comment by xbao** [comment]
@adrian-bl  On the topic of opening the filemanager, how would you feel about having a `View File...` option that sends the appropriate intent? Unless there's already a  easy way to get from song to file that I'm missing?

**Comment by Almtesh** [comment]
Actually, the best way would be to have music stored in directories so you can find yourself the music you want to share with the file manager. This is how I do for ages, even with the player I had from Play store, when I used it.

**Comment by xbao** [comment]
Closing: sharing won't be included in Vanilla at this point. Also, old.

**Pull request closed without merging**
