### PR TITLE
Add open folder button to Playback Activity (for #513)

### PR DESCRIPTION
**Pull request by david-sawatzke**
Implements #513 .
As I don't know much about Java and Android development, this is mostly hacked together. I'm open to suggestions for improvements.

### CODE REVIEW

**Comment by adrian-bl** [comment]
Hi David,

Thanks for the PR and sorry for the delay: The patch looks fine, i just wonder if it wouldn't be nicer (from an UI perspective) to move this functionality into the details-view of the playback activity (eg: where the path, track number and bitrates are displayed).

This way we would save some 'menu space' (which i'd like to keep 'clean') and also add the ability to jump to the genre or artist of the playing song (instead of only jumping to the album). What do you think about this idea?

**Comment by david-sawatzke** [comment]
You mean that you jump to different "selections", depending on where you tap?
I think that could work, but the rows would need to be bigger, because currently it's not easy/possible to exactly tap the individual rows.

Maybe when the extra info is open, tapping on the additional rows would open a dialog, asking by which attribute sould be selected and the title, artist and album rows would continue to just directly select the album?

**Comment by adrian-bl** [comment]
> Maybe when the extra info is open, tapping on the additional rows would open a dialog, asking by 
> which attribute sould be selected and the title, artist and album rows would continue to just directly 
> select the album?

That would be an option - but Android is usually pretty good at finding the correct click consumer ;-)

I don't think that hitting the correct row would be a big issue given the fact that almost all devices are >= 5'' anyway.

**Comment by david-sawatzke** [comment]
I've now added row clickables (genres not yet implemented). There is now a lot of similar code, but I'm not sure how to shorten it.

**Comment by adrian-bl** [comment]
> artistRow.setOnClickListener(this);

I guess you need to do this to consume the long click, but looking at the code, this might crash if the user has a different playback-style selected (as artistRow & co might not exist).

About the duplicate code: Wouldn't it be simpler to just change
```
openLibrary(Song);
```

into

```
openLibrary(Song, int type);
```

?

But looking at the required UI code it seems that things get far too complicated :-/
Maybe it would be better to add a new 'Jump to... > (Title, Artist, Genre)' entry in the context menu?
(Sorry about changing my mind so often ;-) )

**Comment by david-sawatzke** [comment]
I've now shortened the code, but I'm not sure what you mean by "different playback-style"? I can't find anything like that in the settings

**Comment by adrian-bl** [comment]
Closing this PR as the functionality has been implemented in a sub menu in https://github.com/vanilla-music/vanilla/commit/ffe0fe55dfa0206273de907b2b2db9f6cf25fb44

-- but thanks for the pull request!

**Pull request closed without merging**
