### PR TITLE
Option to select between public or private notifications

### PR DESCRIPTION
**Pull request by dennisguse**
A private notification hides the media information.
Public and private notification provide media controls.

### CODE REVIEW

**Comment by Adonai** [comment]
Wow sounds legit!

@adrian-bl look!

**Comment by adrian-bl** [comment]
I dont understand what this is supposed to do: what is the benefit of creating a private notification?

**Comment by dennisguse** [comment]
Quite simple: I don't want to have the currently playing song shown on my lock screen.
I use the Android setting Settings->Notifications->On the lock screen: "Hide sensitive content".
And I consider the currently playing song "sensitive content".

Without this patch, I can only disable Vanilla's notifications to prevent showing the current song on the lock screen.
However, I then don't have the controls for skipping, pause etc on the lock screen.
This is quite inconvenient...

This patch introduces the option to set Vanilla's notifications to "private".
Thus, it is hidden from the lock screen if "hide sensitive content" is set and instead the public notification is shown (only provides media controls).

Actually, I think this should be Vanilla's default behavior.
But adding it as a default "off" option, allows users to decide if they want this or not without changing Vanilla's current behavior.

**Comment by adrian-bl** [comment]
> And I consider the currently playing song "sensitive content".

I don't think that the currently playing song is "sensitive content" in any way: By default, we even broadcast this information to any application that would like to know about it.

I'd rather have an option to change the notification style (with text, without text, maybe more controls)  than using androids public/private notification style.

**Comment by Adonai** [comment]
@adrian-bl , we do broadcast it, but the applications that can see it are behind lock screen too.
And yes, the song info *can* be sensitive content. Maybe you don't listen to songs of such groups like "Pit of Anal Humiliation" but some do.

**Comment by adrian-bl** [comment]
> I don't think optional feature can hurt us in any way.

Every new feature increases the maintenance cost which usually ends up at my desk:
It will require testing and care until eternity - Will it still work on Android 8.x? Who knows. Will it crash on 4.x? Probably.

I'm sorry but i just don't see the use case for this feature: You can already hide the cover on the lockscreen - If you are worried about about people behind you reading the title of the currently playing song, then you should probably just get a screen protector.

**Comment by dennisguse** [comment]
Ok...

So under which circumstances could you consider inclusion of this patch?

I can do the testing for Android 4.x - no problem there.
And I follow your point about maintenance for this feature - but the feature is not that complicated and is actually only a slight change.
About the future of private notifications within Android - well it is available since API level 21 (Android 5.0) and was not substantially changed.
Why should it be changed in Android 8?
In any case, I can take care of the maintenance for this feature.

Any other issues?

**Comment by adrian-bl** [comment]
> So under which circumstances could you consider inclusion of this patch?

As i already said: I really do not consider this to be an issue.
I'd be OK to include a patch which makes the playback controls visible if the notification is set to sensitive, but i don't see the point in adding yet another config option for an obscure feature.

> And I follow your point about maintenance for this feature - but the feature is not that complicated and is 
> actually only a slight change.

It isn't: Every feature increases the testing. Did you test it on 4.x? I'm pretty sure it would crash.

**Pull request closed without merging**
