### PR TITLE
Android6 - gradle

### PR DESCRIPTION
**Pull request by xbao**

### CODE REVIEW

**Comment by xbao** [comment]
@adrian-bl would it be possible to get these merged into master?

**Comment by adrian-bl** [comment]
Sure - this got somehow lost while i stashed the android6 branch.

**Comment by okungnyo** [comment]
Does this mean that the new permission system is now supported?

**Comment by adrian-bl** [comment]
yes: vanilla will request permissions if required.

**Comment by xbao** [comment]
@adrian-bl eeexcellent, ta :)

**Pull request merged**
