### PR TITLE
Add nightly link to About page

### PR DESCRIPTION
**Pull request by xbao**
Screenshot: about_nightly_320

### CODE REVIEW

**Comment by aminb** [comment]
Looks good to me.

Also, it's probably a good idea to set up these redirections for shorter and better looking links:

- `vanillamusic.io/code` --> `github.com/vanilla-music/vanilla`
- `vanillamusic.io/issues` --> `github.com/vanilla-music/vanilla/issues`
- `vanillamusic.io/latest-nightly.apk` --> `android.eqmx.net/android/vanilla/VanillaMusic-nightly.apk`

Pinging @adrian-bl.

**Comment by xbao** [comment]
Good call. Screenshot: 
about_nightly_short_320

**Comment by aminb** [comment]
Nice, that was one of the indirect implications of my comment

Now that I think a bit, it's probably a good idea to keep the github links the same (for source code and issues, github.com is more familiar to the eye than vanillamusic.io), but for the nightly I still think `vanillamusic.io/latest-nightly.apk` looks much better than the current [temporary] one we have.

**Comment by xbao** [comment]
Oops, I must have misread your comment. Haha, my bad. Yes, agreed on vanillamusic.io redirection for the apk. I really like the redirections for the github urls, but agree that the user would find github.com more familiar. Maybe we could throw a couple of tiny github icons in there?

**Comment by aminb** [comment]
> Oops, I must have misread your comment. Haha, my bad. Yes, agreed on vanillamusic.io redirection for the apk.

Hahaha, it's fine, getting read of protocols is nice too IMHO.

> I really like the redirections for the github urls, but agree that the user would find github.com more familiar. Maybe we could throw a couple of tiny github icons in there?

Sure, let's see what @adrian-bl thinks :)

**Comment by adrian-bl** [comment]
I'd keep the github.com URLs: People know the domain and know, that they already have an account there to report bugs and stuff.

But the redirect for the APK would be a nice thing, as 'eqmx.net' isn't such a great domain ;-)

**Comment by xbao** [comment]
Completely forgot about this.

> But the redirect for the APK would be a nice thing, as 'eqmx.net' isn't such a great domain ;-)

It's a great domain! 4 character .net domains are rare beasts these days. It's not quite as related to Vanilla as the .io one though :) 

Does anyone know what's involved in setting up the redirect for the nightly APK? Web services are not my strong suit...

**Comment by xbao** [comment]
Added simple link in commit 39437ec28719194a845b31e456d7c8b72d7507d7, pushed to master.

**Pull request closed without merging**
