### PR TITLE
Added functionality to set song as ringtone

### PR DESCRIPTION
**Pull request by folol**
In Song fragment , a menu item titled "Set As Ringtone" is added to context menu , if selected will make the specified song , default Ringtone of the user's mobile .

### CODE REVIEW

**Comment by adrian-bl** [comment]
Thanks for your PR, but i'm not sure if we really should include this feature in vanilla music - i never had the need to use a music player to set a custom ringtone, but maybe it's just me ;-)

@aminb @xbao What do you guys think? Would it be an useful addition?

**Comment by folol** [comment]
Yes you are right , its personnel choice  .....i would like to have such an option in my music player
If an user is listening to a song and he wants to make it ringtone then it will be more convenient to him to set song as ringtone in just two clicks instead of going to settings and then sound and then .....

**Comment by xbao** [comment]
My 2c: I don't think it would be used enough to justify A) the two extra
permissions and B) adding another option to an already crowded context
menu, though I can understand the desire to simplify the process if
you're doing it often.  My phone's always on vibrate and the last ringtone I set was on a phone whose makers thought 50 SMS messages was plenty, so probably not the best 'man/woman on the street' opinion.

I do have concerns with the implementation. It deletes the selected song from the media store then re-adds it as a ringtone, effectively removing it from the library and all the playlists it was in. Presumably this isn't intended behaviour?

**Comment by xbao** [comment]
Closing due to lack of reply.

**Pull request closed without merging**
